### ISSUE TITLE
full dehydrate for subnet

### ISSUE THREAD

**Issue by paras-dave** [SynapseFI/SynapseNode#43]
Can seem to pass in option `full_dehydrate` to `user.getSubnet`

**Comment by dguo** [comment]
This was resolved by https://github.com/SynapseFI/SynapseNode/pull/59.

**Comment by jenstroeger** [comment]
@dguo, feel free to close this issue if it’s a duplicate.

**Comment by dguo** [comment]
I can't close this issue because I didn't open it, and I'm not a Synapse member.
