### ISSUE TITLE
Verification API calls are missing

### ISSUE THREAD

**Issue by dguo** [SynapseFI/SynapseNode#47]
It would be nice if this library could support the [verify address](https://docs.synapsefi.com/reference#verify-address) and [verify routing number](https://docs.synapsefi.com/reference#verify-routing-number) requests.

**Comment by jenstroeger** [comment]
@thewalrusmaximus and @jasonto1, who would own change requests like this one?

**Comment by jasonto1** [comment]
They've both been added: https://github.com/SynapseFI/SynapseNode/blob/f833e8159cfb23a9c667f455abddce01d56026dc/src/lib/Client.js#L211-L222

and 
https://github.com/SynapseFI/SynapseNode/blob/f833e8159cfb23a9c667f455abddce01d56026dc/src/lib/Client.js#L225-L232

**Comment by jenstroeger** [comment]
@dguo, if this is what you’re looking for then please feel free to close this issue.

**Comment by dguo** [comment]
Thanks!
